### ISSUE TITLE
OpenShift Virtualization testing - Creating Snapshots & Reverting Back and Forth to Those Snapshots

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#754] opened 2024-10-02 11:29 UTC
# OpenShift Virtualization testing - Creating Snapshots & Reverting Back and Forth to Those Snapshots

## Motivation
The ability to create and manage snapshots of virtual machines, allowing to easily revert to previous states.  
This is essential for ensure data safety, enable rollback after updates, and supporting test and development usecases.

## Completion Criteria
- Users are able to create snapshots of the virtual machines.
- Users are able to revert to previous snapshots efficient and without data loss.
- Documentation is provided on how to create and manage snapshots.

## Description
- [ ] Implement the ability to create snapshots for virtual machines in OpenShift Virtualization.
- [ ] Implement the ability to revert virtual machines to previously created snapshots.
- [ ] Create documentation and provide examples for creating, managing, and reverting snapshots.

## Completion dates
Desired - TBD 
Required - TBD

**Comment by computate** [comment] 2024-10-02 19:41
@schwesig I think this is a duplicate of https://github.com/nerc-project/operations/issues/722 which I already tested and closed.

**Closed** 2024-10-22 15:19 UTC
Labels: duplicate
