### ISSUE TITLE
Assist the EC440 class lecture 

### ISSUE THREAD

**Issue by IsaiahStapleton** [nerc-project/operations#409] opened 2024-01-24 15:21 UTC
I will be assisting the EC440 class along with Larry Woodman. We will have office hours on Monday and Wednesday from 1-4. The class lecture is Monday and Wednesday from 4:30-6:15pm.

**Comment by joachimweyl** [comment] 2024-01-30 13:43
assuming 6 hours a week at 3 weeks for this sprint I am setting the Estimate to 3 story points. Please create a duplicate of this issue for the next sprint.

**Closed** 2024-03-05 19:15 UTC
Labels: ope
