### ISSUE TITLE
Adding Customer Code as a new Allocation attribute

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#269] opened 2023-10-13 16:24 UTC
- Need for both OpenStack and OpenShift resource allocations

**Comment by jtriley** [comment] 2023-10-13 17:30
@knikolla Would this be better off as a feature upstream? Seems a bit out of scope for the `coldfront-plugin-cloud` repo and would be more broadly useful/applicable to all coldfront users regardless of the service(s) they allocate.

**Comment by joachimweyl** [comment] 2023-10-17 19:32
@joachimweyl track down the duplicate link it to this one and close this.

**Comment by knikolla** [comment] 2023-10-19 19:01
@jtriley Upstream ColdFront doesn't have any invoicing features whereas we have started incorporating this kind of features into the plugin. Therefore it seems to make sense for now to keep putting those features there.

**Comment by joachimweyl** [comment] 2023-10-25 13:44
duplicate of https://github.com/nerc-project/operations/issues/223

**Closed by joachimweyl** 2023-10-25 13:44 UTC
