### ISSUE TITLE
xdmod failing to pull images from docker hub

### ISSUE THREAD

**Issue by jtriley** [nerc-project/operations#70] opened 2023-01-10 20:58 UTC
After rebuilding the infra cluster we're getting errors in xdmod pods pulling various images which eventually causes us to hit a pull rate limit with docker hub, e.g.:

mariadb:

```
Failed to pull image "mariadb:10.3.34": rpc error: code = Unknown desc = loading manifest for target platform: reading manifest sha256:50b2b331cac391840255a45a7db888a05cd3aae3ca3c4f8aa15f7ae720820908 in docker.io/library/mariadb: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

python:

```
Pulling image python:3.9.0 ...
Resolving "python" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull registry.redhat.io/python:3.9.0...
time="2023-01-10T15:28:08Z" level=warning msg="failed, retrying in 1s ... (1/3). Error: initializing source docker://registry.redhat.io/python:3.9.0: reading manifest 3.9.0 in registry.redhat.io/python: unknown: Not Found"
time="2023-01-10T15:28:09Z" level=warning msg="failed, retrying in 2s ... (2/3). Error: initializing source docker://registry.redhat.io/python:3.9.0: reading manifest 3.9.0 in registry.redhat.io/python: unknown: Not Found"
time="2023-01-10T15:28:12Z" level=warning msg="failed, retrying in 4s ... (3/3). Error: initializing source docker://registry.redhat.io/python:3.9.0: reading manifest 3.9.0 in registry.redhat.io/python: unknown: Not Found"
```

There might be more?

**Comment by jtriley** [comment] 2023-01-10 20:59
Looks like similar issue with `python:3.9` image:

```
Pulling image python:3.9.0 ...
Resolving "python" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull registry.redhat.io/python:3.9.0...
time="2023-01-10T15:28:08Z" level=warning msg="failed, retrying in 1s ... (1/3). Error: initializing source docker://registry.redhat.io/python:3.9.0: reading manifest 3.9.0 in registry.redhat.io/python: unknown: Not Found"
time="2023-01-10T15:28:09Z" level=warning msg="failed, retrying in 2s ... (2/3). Error: initializing source docker://registry.redhat.io/python:3.9.0: reading manifest 3.9.0 in registry.redhat.io/python: unknown: Not Found"
time="2023-01-10T15:28:12Z" level=warning msg="failed, retrying in 4s ... (3/3). Error: initializing source docker://registry.redhat.io/python:3.9.0: reading manifest 3.9.0 in registry.redhat.io/python: unknown: Not Found"
```

Perhaps these tags have been removed upstream?

**Comment by msdisme** [comment] 2023-01-11 16:30
Are other parts of the reinstall also hitting docker from the same ip address?  Looking at https://docs.docker.com/docker-hub/download-rate-limit/ it seems like this is potentially a larger problem then just xdmod.

**Comment by larsks** [comment] 2023-01-11 17:12
The error message provides the cause and the solution:

> You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

This isn't a new issue; Docker has fairly strict rate limits on their repositories.

Currently the default pull secret doesn't have any Docker credentials. We can either:

- [Add someone's credentials to the default pull secret](https://docs.openshift.com/container-platform/4.10/openshift_images/managing_images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secrets), or
- Create an application-specific pull secret in the `xdmod` project

We can also cache images in the local image registry and pull them from there rather than from Docker.

**Comment by rob-baron** [comment] 2023-01-12 19:05
Here are some other possibilities:

( https://medium.com/rossum/how-to-overcome-docker-hub-pull-limits-in-a-kubernetes-cluster-382f317accc1 )

We do need a more general solution as this is a common problem.  I would be fine with

1. if we open up the internal docker registry so that we can push the required images there, then we leave it up to the individuals who are deploying the software/service to load the images in. 

2. Any sort of mirroring that is automated.

**Comment by joachimweyl** [comment] 2023-01-17 13:46
This is something that @jtriley and the NERC team will need to maintain. Justin, what is your preference for this?

**Comment by rob-baron** [comment] 2023-01-17 14:58
Since this isn't an issue that either @tzumainn or I can do anything about, I am going to pass it back to @jtriley

**Comment by joachimweyl** [comment] 2023-02-08 18:45
related to #79

**Comment by larsks** [comment] 2023-08-31 19:43
@joachimweyl I think we should close this issue.

**Comment by joachimweyl** [comment] 2023-08-31 19:52
We can reopen it if the need arrises.

**Closed by joachimweyl** 2023-08-31 19:52 UTC
Labels: openshift
