### ISSUE TITLE
Test OPE book image in production RHODs cluster in NERC

### ISSUE THREAD

**Issue by hpdempsey** [nerc-project/operations#216] opened 2023-08-30 18:00 UTC
Isaiah Stapleton will test the new production RHODS build with the testbook image from the BU Operating Systems class to make sure that it functions as well as it does in ROSA (the AWS RHODS environment).  Justin says we can do this after we create a new project for this, so Heidi will create that and add Isaiah to it.

**Comment by joachimweyl** [comment] 2023-09-18 19:06
@dystewart Isaiah mentioned you had offered to create a PR to create a namespace for this issue. I was unable to track down that PR. Can you please provide a link for that PR?

**Comment by IsaiahStapleton** [comment] 2023-09-27 18:09
I have started testing the current ROSA class OPE image, everything looks good so far. I need to also test the new base OPE image (needed some fixes that just got integrated). Also need to confirm that the base OPE image works for the flows that Milson was using on NERC.

**Comment by IsaiahStapleton** [comment] 2023-10-04 17:20
I have tested the current base ope image. Everything looks good and is functioning as expected.

**Comment by IsaiahStapleton** [comment] 2023-10-10 15:29
@joachimweyl That is still the plan. I am unable to close this ticket myself and I forgot to ask someone to close it. I created a new ticket that is related to this here: https://github.com/nerc-project/operations/issues/255. So as I've already done some manual testing of the OPE book images, we are now working on creating a test book that can be used to test different aspects of the OPE containers by simply running a notebook full of test cases that tell you what things worked and what failed. So that way when there is an OpenShift or RHODS update we can easily run these tests to make sure things are still functioning correctly after the update.

**Comment by joachimweyl** [comment] 2023-10-10 15:32
Closing as duplicate of https://github.com/nerc-project/operations/issues/255

**Closed by joachimweyl** 2023-10-10 15:32 UTC
Labels: duplicate
