### ISSUE TITLE
Hypershift test cluster tracking issue

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#205] opened 2023-08-28 17:32 UTC
This issue tracks all the tasks in our Hypershift test deployment.

- [ ] #204
- [ ] #206
- [ ] #213
- [ ] #207
- [ ] #208
- [ ] #209
- [ ] #210
- [ ] #211

**Comment by joachimweyl** [comment] 2023-08-29 20:18
duplicate of https://github.com/CCI-MOC/epics/issues/73

**Closed by joachimweyl** 2023-08-29 20:18 UTC
