### ISSUE TITLE
Switch down, nic1 for all devices in r1-pc-c20 are disconnected

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#348] opened 2023-12-12 16:41 UTC
See [slack conversation](https://massopencloud.slack.com/archives/C027TDE52TZ/p1702397626092649) for complete details.

```
augustin
  11 minutes ago
that whole chassis cmc-9  r1-pc-c20 (I think?) in U25..   net passthrough module A has no links
jtriley
  9 minutes ago
Possibly related: according to Christian one of the data switches in 1-C-20 went down recently due to failing fans. Need to have tech square folks (or if Hakan is on site...) grab some serial numbers in order to get replacement fans.
one of the two switches shut itself down due to two fans failing. touching base with nick to determine how to get those replaced
can you ask if they can grab the serial numbers off the switches in 1-c-20. theyre not currently under our service contract so i need to get them added to that before i can get the replacement fans
augustin
  8 minutes ago
so  that would probably mean NIC1 on all FX nodes in that rack
:heavy_check_mark:
1

larsks
  7 minutes ago
:cry:
augustin
  7 minutes ago
:face_vomiting::gun:
jtriley
  7 minutes ago
prod worker nodes are still up - checking bond status there which would show that
jtriley
  5 minutes ago
confirmed nic1 appears to be down on the active worker nodes on prod cluster
```

**Comment by aabaris** [comment] 2023-12-12 16:50
A switch has failed in R1-PC-C20 U39 (sw1a)

Parts  (cooling fans) are being shipped and should be arriving tomorrow 2023-12-13.

We would like to request someone from tech square to perform fan replacement on the switch.  

Shipping details to follow.

**Comment by imstof** [comment] 2023-12-12 17:05
No problem. We'll get the part swapped out as soon it arrives. Just let us know the shipping details when you get them.

**Comment by aabaris** [comment] 2023-12-13 18:02
> No problem. We'll get the part swapped out as soon it arrives. Just let us know the shipping details when you get them.

I believe the persons who would have and relay to me the tracking info are on all day-all-hands event.  As soon as I get the tracking info I will post update to this thread.  As far as i can see, you guys are blocked on this task until tracking information is provided to you.   - Augustine

**Comment by jtriley** [comment] 2023-12-13 20:58
From Christian earlier today:
```
Carrier:	FLASH	2126553
at least one was delivered but there may be 2 in the box
it was mailed to harvard university-christian ranney
prob wait til tomorrow. eta 430
it’ll be the only two small boxes in my name. the other box is a large switch
```

**Comment by yani4** [comment] 2023-12-14 17:27
I picked up one box with Christian's name on it and it has a singular fan.
I don't recall seeing a second mailed to harvard university-christian ranney but could have missed it.

**Comment by yani4** [comment] 2023-12-14 19:15
Found the second box.
Was sent via ups which threw me off.

I'll be swapping out the fans soon.

**Comment by yani4** [comment] 2023-12-14 20:20
I swapped both fans and it looks like the switch is back online from my end.
It looks like they have return labels so I'm guessing that they need to be sent back to complete the rma.
I'll get it packed up for that so that the fans can go out tomorrow

**Comment by aabaris** [comment] 2023-12-14 21:44
Looks much better.  The down links are now active.    @jtriley would it be worth asking Nick or Christian to confirm the switche no longer reporting any errors before closing this issue as resolved?

**Comment by jtriley** [comment] 2023-12-15 15:19
@aabaris I'm having them check the switch and will report back.
@yani4 Thank you, please box the old ones as they will need to be shipped back.

**Comment by yani4** [comment] 2023-12-15 15:20
@jtriley already packed them up and stuck the shipping labels that were in the boxes on the outside.

**Comment by jtriley** [comment] 2023-12-18 17:03
Just confirmed things look good from the switch now. Closing. @yani4 can you please be sure to drop the old fans in the shipping room on the outgoing mail table? Thanks!

**Closed by jtriley** 2023-12-18 17:03 UTC
Labels: techsquare
